"""Auto-generated by day30_pytest_generator. DO NOT EDIT."""
import pytest
import requests

BASE_URL: str = "http://127.0.0.1:8768"
VALID_TOKEN: str = "demo-token-123"


@pytest.fixture
def base_url() -> str:
    return BASE_URL


@pytest.fixture
def auth_headers() -> dict[str, str]:
    return {"Authorization": f"Bearer {VALID_TOKEN}"}
