"""Auto-generated by day30_pytest_generator. DO NOT EDIT."""
import pytest
import requests

BASE_URL: str = "http://127.0.0.1:8768"


def _request(method: str, path: str, base_url: str, body: dict[str, str] | None = None, headers: dict[str, str] | None = None):
    url: str = f"{base_url}{path}"
    return requests.request(method, url, json=body or None, headers=headers or {}, timeout=5)


def _assert_field(resp, field: str) -> None:
    value = resp.json()
    for key in field.split("."):
        assert isinstance(value, dict), f"响应体字段路径断裂: {field} 的 {key}"
        value = value[key]


class TestApiRefund:

    def test_normal(self, base_url):
        resp = _request("post", "/api/refund", base_url, body={"order_id": "ORD-1001", "amount": "99.5"}, headers={})
        assert resp.status_code == 200, f"期望 200 实际 {resp.status_code}: {resp.text[:200]}"
        _assert_field(resp, "code")
        _assert_field(resp, "data.refund_id")

    @pytest.mark.parametrize("payload", [
        {"amount": "99.5"},
        {"order_id": "ORD-1001"},
    ])
    def test_missing_params(self, base_url, payload):
        resp = _request("post", "/api/refund", base_url, body=payload)
        assert resp.status_code == 400, f"期望 400 实际 {resp.status_code}: {resp.text[:200]}"

    def test_invalid_credentials(self, base_url):
        resp = _request("post", "/api/refund", base_url, body={"order_id": "invalid_value", "amount": "99.5"})
        assert resp.status_code == 401, f"期望 401 实际 {resp.status_code}: {resp.text[:200]}"
