"""
Day 30 练习 3：pytest 代码渲染器 —— ApiDoc/计划 → conftest.py + test_api_suite.py（确定性模板）

设计（步骤 1 决策 B/C 落地）：
  - 模型只出接口语义（ApiDoc），pytest 代码由这里确定性渲染：
    语法稳定、风格统一、同输入同输出（可 diff 可评审）
  - 行列表拼接（不用 f-string 大模板）：pytest 代码里全是 {}（dict/函数体/f-string），
    再套一层 f-string 就是花括号地狱 → 渲染层全部用字符串拼接，生成代码里的 {} 原样保留
  - 每端点一个 Test 类，三件套必出（正常/参数缺失/越权或错误凭据）——学习计划硬性要求
  - parametrize 的 argvalues 必须是 list 字面量（pytest 9.1.0 起生成器/迭代器已弃用，
    2026-06-13 联网确认：可迭代对象会被耗尽导致用例静默丢失）
  - ast.parse 校验：语法可编译才落盘（正确性第一层；行为正确性靠练习 4 真实执行）

用法：
  python -c "from day30_pytest_generator import exp3_render_smoke; exp3_render_smoke()"  # 零 API
"""
import ast
import os
import sys

if sys.platform == "win32":
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")  # type: ignore[attr-defined]

from day30_api_schema import (
    ApiDoc,
    CATEGORY_LABEL,
    EndpointPlan,
    PlanCase,
    VALID_TOKEN,
    generate_api_plan,
    load_api_plan,
    render_plan_markdown,
)

# ═══════════════════════════════════════════════════════
# 渲染：行列表拼接（模板即代码，f-string 只用于渲染层自己的占位）
# ═══════════════════════════════════════════════════════

def render_conftest(api_doc: ApiDoc) -> str:
    """conftest.py：BASE_URL 常量 + base_url/auth_headers 两个 fixture（学习计划要求）。"""
    lines: list[str] = [
        '"""Auto-generated by day30_pytest_generator. DO NOT EDIT."""',
        "import pytest",
        "import requests",
        "",
        f'BASE_URL: str = "{api_doc.base_url}"',
        f'VALID_TOKEN: str = "{VALID_TOKEN}"',
        "",
        "",
        "@pytest.fixture",
        "def base_url() -> str:",
        "    return BASE_URL",
        "",
        "",
        "@pytest.fixture",
        "def auth_headers() -> dict[str, str]:",
        '    return {"Authorization": f"Bearer {VALID_TOKEN}"}',
        "",
    ]
    return "\n".join(lines)


def render_test_module(api_doc: ApiDoc, plans: list[EndpointPlan]) -> str:
    """test_api_suite.py：请求 helper + 断言 helper + 每端点一个 Test 类。"""
    lines: list[str] = [
        '"""Auto-generated by day30_pytest_generator. DO NOT EDIT."""',
        "import pytest",
        "import requests",
        "",
        f'BASE_URL: str = "{api_doc.base_url}"',
        "",
        "",
        "def _request(method: str, path: str, base_url: str, body: dict[str, str] | None = None, headers: dict[str, str] | None = None):",
        "    url: str = f\"{base_url}{path}\"",
        "    return requests.request(method, url, json=body or None, headers=headers or {}, timeout=5)",
        "",
        "",
        "def _assert_field(resp, field: str) -> None:",
        "    value = resp.json()",
        "    for key in field.split(\".\"):",
        "        assert isinstance(value, dict), f\"响应体字段路径断裂: {field} 的 {key}\"",
        "        value = value[key]",
        "",
        "",
    ]
    for plan in plans:
        lines.append(f"class Test{_class_name(plan.path)}:")
        lines.append("")
        for case in plan.cases:
            lines.extend(_render_case_lines(case))
            lines.append("")
    return "\n".join(lines)


def _class_name(path: str) -> str:
    """接口路径 → ASCII 测试类名：/api/login → TestApiLogin；/api/orders → TestApiOrders。

    ⚠️ 确定性转换（endpoint.name 是中文，不能进类名；path 是 ASCII 且稳定）。
    """
    parts: list[str] = [p for p in path.strip("/").replace("-", "_").split("/") if p]
    name: str = "".join(p.capitalize() for p in parts) or "Root"
    return f"{name}"


def _dict_literal(data: dict[str, str]) -> str:
    """dict → Python 字面量字符串（key 用双引号，值原样）。

    ⚠️ 不用 json.dumps 直接拼：生成代码里是 Python dict 字面量，引号风格要一致。
    """
    if not data:
        return "{}"
    items: list[str] = [f'"{k}": "{v}"' for k, v in data.items()]
    return "{" + ", ".join(items) + "}"


def _render_case_lines(case: PlanCase) -> list[str]:
    """一条计划用例 → pytest 代码行（按 category 分派渲染）。"""
    method_lower: str = case.http_method.lower()
    if case.category == "normal":
        return _render_normal(case, method_lower)
    if case.category == "missing":
        return _render_missing(case, method_lower)
    if case.category == "unauthorized":
        return _render_unauthorized(case, method_lower)
    return _render_invalid_credentials(case, method_lower)


def _render_normal(case: PlanCase, method_lower: str) -> list[str]:
    lines: list[str] = [
        "    def test_normal(self, base_url):",
        f"        resp = _request(\"{method_lower}\", \"{case.path}\", base_url, "
        f"body={_dict_literal(case.body)}, headers={_dict_literal(case.headers)})",
        f"        assert resp.status_code == {case.expected_status}, "
        f"f\"期望 {case.expected_status} 实际 {{resp.status_code}}: {{resp.text[:200]}}\"",
    ]
    for field in case.response_fields:
        lines.append(f'        _assert_field(resp, "{field}")')
    return lines


def _render_missing(case: PlanCase, method_lower: str) -> list[str]:
    variants_literal: str = ",\n        ".join(
        _dict_literal(v) for v in case.variants
    )
    return [
        "    @pytest.mark.parametrize(\"payload\", [",
        f"        {variants_literal},",
        "    ])",
        "    def test_missing_params(self, base_url, payload):",
        f"        resp = _request(\"{method_lower}\", \"{case.path}\", base_url, body=payload)",
        f"        assert resp.status_code == {case.expected_status}, "
        f"f\"期望 {case.expected_status} 实际 {{resp.status_code}}: {{resp.text[:200]}}\"",
    ]


def _render_unauthorized(case: PlanCase, method_lower: str) -> list[str]:
    variants_literal: str = ",\n        ".join(
        _dict_literal(v) for v in case.variants
    )
    return [
        "    @pytest.mark.parametrize(\"headers\", [",
        f"        {variants_literal},",
        "    ])",
        "    def test_unauthorized(self, base_url, headers):",
        f"        resp = _request(\"{method_lower}\", \"{case.path}\", base_url, headers=headers)",
        f"        assert resp.status_code == {case.expected_status}, "
        f"f\"期望 {case.expected_status} 实际 {{resp.status_code}}: {{resp.text[:200]}}\"",
    ]


def _render_invalid_credentials(case: PlanCase, method_lower: str) -> list[str]:
    return [
        "    def test_invalid_credentials(self, base_url):",
        f"        resp = _request(\"{method_lower}\", \"{case.path}\", base_url, "
        f"body={_dict_literal(case.body)})",
        f"        assert resp.status_code == {case.expected_status}, "
        f"f\"期望 {case.expected_status} 实际 {{resp.status_code}}: {{resp.text[:200]}}\"",
    ]


# ═══════════════════════════════════════════════════════
# 语法校验 + 落盘（正确性第一层：可编译）
# ═══════════════════════════════════════════════════════

def validate_python_syntax(code: str, label: str) -> None:
    """ast.parse 校验生成代码（可编译保证；不通过直接抛 SyntaxError）。"""
    try:
        ast.parse(code)
    except SyntaxError as exc:
        raise SyntaxError(f"{label} 语法错误: {exc}") from exc


def save_generated_tests(api_doc: ApiDoc, plans: list[EndpointPlan], out_dir: str) -> tuple[str, str]:
    """渲染 + 校验 + 落盘 conftest.py 与 test_api_suite.py，返回 (conftest_path, test_path)。"""
    os.makedirs(out_dir, exist_ok=True)
    conftest_code: str = render_conftest(api_doc)
    test_code: str = render_test_module(api_doc, plans)
    validate_python_syntax(conftest_code, "conftest.py")
    validate_python_syntax(test_code, "test_api_suite.py")
    conftest_path: str = os.path.join(out_dir, "conftest.py")
    test_path: str = os.path.join(out_dir, "test_api_suite.py")
    with open(conftest_path, "w", encoding="utf-8") as f:
        f.write(conftest_code)
    with open(test_path, "w", encoding="utf-8") as f:
        f.write(test_code)
    return conftest_path, test_path


def generate_api_tests_from_plan(plan_json: str, out_dir: str) -> tuple[str, str] | None:
    """从已落盘 plan json 读回 ApiDoc（不重跑 LLM）→ 确定性再生成 plan → 渲染 → 落盘。

    ⚠️ 执行对象 = 评审对象：代码来自评审过的 json，不是直接来自 LLM 输出（Day 28 评审门迁移）。
    """
    api_doc: ApiDoc | None = load_api_plan(plan_json)
    if api_doc is None:
        print(f"❌ plan json 读回失败: {plan_json}")
        return None
    plans: list[EndpointPlan] = generate_api_plan(api_doc)
    return save_generated_tests(api_doc, plans, out_dir)


# ═══════════════════════════════════════════════════════
# 实验
# ═══════════════════════════════════════════════════════

def exp3_render_smoke() -> None:
    """实验 3：渲染器冒烟（零 API）——构造 ApiDoc → 渲染 → ast 校验 → 断言关键行。"""
    print("=" * 60)
    print("实验：exp3_render_smoke —— pytest 渲染器（零 API）")
    from day30_api_schema import ApiEndpoint, ApiParam  # noqa: PLC0415

    api_doc = ApiDoc(
        title="登录服务接口", base_url="http://127.0.0.1:8766",
        endpoints=[
            ApiEndpoint(
                name="用户登录", method="POST", path="/api/login", auth_required=False,
                expected_status=200, error_status=400, unauthorized_status=401,
                response_fields=["code", "data.token"],
                params=[
                    ApiParam(name="phone", location="body", required=True, param_type="string",
                             example="13800138000", description="11 位手机号"),
                    ApiParam(name="password", location="body", required=True, param_type="string",
                             example="Test123456", description="不少于 8 位"),
                ],
            ),
        ],
    )
    plans = generate_api_plan(api_doc)
    conftest_code: str = render_conftest(api_doc)
    test_code: str = render_test_module(api_doc, plans)
    validate_python_syntax(conftest_code, "conftest")
    validate_python_syntax(test_code, "test module")

    # 断言关键行（模板结构 = 验收标准）
    assert 'BASE_URL: str = "http://127.0.0.1:8766"' in conftest_code
    assert "def auth_headers() -> dict[str, str]:" in conftest_code
    assert "class TestApiLogin:" in test_code
    assert "def test_normal(self, base_url):" in test_code
    assert "@pytest.mark.parametrize(\"payload\", [" in test_code
    assert "def test_missing_params(self, base_url, payload):" in test_code
    assert "def test_invalid_credentials(self, base_url):" in test_code
    assert "assert resp.status_code == 401" in test_code
    assert '_assert_field(resp, "data.token")' in test_code
    # parametrize 的 argvalues 是 list 字面量（pytest 9 弃用迭代器，2026-06-13 联网确认）
    assert '{"password": "Test123456"},' in test_code and '{"phone": "13800138000"},' in test_code

    print(conftest_code)
    print("---")
    print(test_code[:1500])
    print("  ✅ ast.parse 通过 + 关键行断言全绿（三件套结构 + parametrize list + 断言写法）")
    print("✅ 渲染器冒烟全部通过")



if __name__ == "__main__":
    exp3_render_smoke()
    print("\n💡 要点回顾：")
    print("   pytest 代码 = 确定性模板渲染（不是模型写）——语法稳定、可 diff、ast 校验")
    print("   行列表拼接避开 f-string 花括号地狱；parametrize 必须 list（pytest 9）")
